repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix, --trailing-comma]
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.8.0
  hooks:
  - id: setup-cfg-fmt
    args: [--min-py-version, '3.13']
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.15.0
  hooks:
  - id: reorder-python-imports
    args: [--py313-plus, --add-import, from __future__ import annotations]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0
  hooks:
  - id: ruff-check
    args: [ --fix ]
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.16.1
  hooks:
  - id: mypy
    language_version: python3.13
